# Generated by Django 4.1.7 on 2023-03-18 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="birth",
            new_name="dateofbirth",
        ),
    ]
