# Generated by Django 4.1.7 on 2023-03-08 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="age",
        ),
    ]
