# Generated by Django 4.1.7 on 2023-03-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0002_remove_userinfo_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
