# Generated by Django 4.1.7 on 2023-03-16 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0004_userinfo_remark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="name",
            new_name="email",
        ),
    ]
