# Generated by Django 4.1.7 on 2023-03-18 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0005_rename_name_userinfo_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="birth",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="phone_number",
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
