# Generated by Django 4.1.7 on 2023-03-18 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0006_userinfo_birth_userinfo_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="birth",
            new_name="dateofbirth",
        ),
    ]
