# Generated by Django 4.1.7 on 2023-03-18 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0008_remove_userinfo_dateofbirth"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="dateofbirth",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
