# Generated by Django 4.1.7 on 2023-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0010_alter_userinfo_dateofbirth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="dateofbirth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
