# Generated by Django 4.1.7 on 2023-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0011_alter_userinfo_dateofbirth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="dateofbirth",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
