# Generated by Django 4.1.7 on 2023-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0013_remove_userinfo_dateofbirth"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="birth",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
