# Generated by Django 4.1.7 on 2023-03-18 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0014_userinfo_birth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="phone_number",
            new_name="phonenumber",
        ),
    ]
