# Generated by Django 4.1.7 on 2023-03-18 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FirstProgramme", "0015_rename_phone_number_userinfo_phonenumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="phonenumber",
            new_name="phone",
        ),
    ]
